In [2]:
import numpy as np

In [14]:
x = [[1,2],[3,4]]
total = 0
for i in x:
    total += sum(i)
print(total)

10


In [13]:
del(sum)

In [15]:
x = [[1,2],[3,4]]
nx = np.array(x)

In [17]:
print(nx.sum())
print(nx.min())
print(nx.max())
print(nx.mean())
print(nx.std())
print(nx.var())

10
1
4
2.5
1.118033988749895
1.25


In [18]:
type(nx)

numpy.ndarray

In [21]:
print(nx.shape) # shape of matrix
print(nx.size) # total elements
print(nx.dtype) # types of elements

(2, 2)
4
int32


In [29]:
z = [[1,2,5],[3,4,5],[5,6,5]]
pp = np.array(z)

In [30]:
print(pp.shape)

(3, 3)


functions to create matrix
 - `arange` - create a range of numbers
 - `linspace` - create a matrix of specified numbers of elements 
 - `ones` - create a matrix of ones
 - `zeros` - create a matrix of zero
 - `random.randint` - create a matrix of random integers
 - `random.rand` - create a matrix of random floats
 - `diag` - create a matrix with diagonal elements

In [31]:
a = np.arange(1,50)
print(a)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49]


In [36]:
np.arange(1,5,.2)

array([1. , 1.2, 1.4, 1.6, 1.8, 2. , 2.2, 2.4, 2.6, 2.8, 3. , 3.2, 3.4,
       3.6, 3.8, 4. , 4.2, 4.4, 4.6, 4.8])

In [37]:
np.arange(1,5,.2).size

20

In [39]:
np.linspace(1,100,10)

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

In [40]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [41]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [44]:
np.ones((3,3), dtype=int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [46]:
np.zeros((10,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [47]:
np.random.randint(1,100,10)

array([ 5, 47, 50, 65, 18, 76, 34,  7, 58,  6])

In [49]:
print(np.random.randint(-5,6,(5,5)))

[[ 2  2 -1  3  2]
 [ 1  0  1  5 -4]
 [ 2 -3  2 -5 -1]
 [ 1 -3 -3  4  3]
 [ 4 -5  0  1 -2]]


In [50]:
np.random.rand(5)  # number of elements

array([0.74565493, 0.76639903, 0.46395532, 0.24699948, 0.87433891])

In [58]:

np.set_printoptions(precision=2)
np.random.rand(15,5) # 10x10 matrix

array([[0.2 , 0.  , 0.24, 0.96, 0.91],
       [0.87, 0.06, 0.98, 0.39, 0.21],
       [0.57, 0.88, 0.81, 0.42, 0.43],
       [0.18, 0.36, 0.11, 0.52, 0.91],
       [0.42, 0.36, 0.41, 0.75, 0.98],
       [0.48, 0.26, 0.46, 0.43, 0.02],
       [0.24, 0.65, 0.17, 0.29, 0.22],
       [0.83, 0.93, 0.6 , 0.41, 0.78],
       [0.99, 0.23, 0.83, 0.77, 0.05],
       [0.64, 0.18, 0.82, 0.26, 0.  ],
       [0.05, 0.65, 0.76, 0.83, 0.36],
       [0.51, 0.79, 0.63, 0.96, 1.  ],
       [0.57, 0.02, 0.23, 0.7 , 0.54],
       [0.44, 0.27, 0.47, 0.79, 0.48],
       [0.83, 0.63, 0.81, 0.75, 0.32]])

In [59]:
x = [1,2,3,4,5]  # make diagonal matrix
np.diag(x)

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

In [64]:
# reshape 
np.arange(10).reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [72]:
x = np.linspace(1,5,25) .reshape(5,5)

In [73]:
x.flatten()

array([1.  , 1.17, 1.33, 1.5 , 1.67, 1.83, 2.  , 2.17, 2.33, 2.5 , 2.67,
       2.83, 3.  , 3.17, 3.33, 3.5 , 3.67, 3.83, 4.  , 4.17, 4.33, 4.5 ,
       4.67, 4.83, 5.  ])

In [75]:
y = np.arange(1, 26).reshape(5,5)
print(y)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [76]:
y.T

array([[ 1,  6, 11, 16, 21],
       [ 2,  7, 12, 17, 22],
       [ 3,  8, 13, 18, 23],
       [ 4,  9, 14, 19, 24],
       [ 5, 10, 15, 20, 25]])

In [78]:
a = np.random.randint(1,10,(3,3))
b = np.random.randint(1,10,(3,3))
print(a)
print(b)

[[9 1 7]
 [6 8 8]
 [6 1 8]]
[[8 3 5]
 [8 5 5]
 [6 1 7]]


In [79]:
a + b

array([[17,  4, 12],
       [14, 13, 13],
       [12,  2, 15]])

In [80]:
a * b

array([[72,  3, 35],
       [48, 40, 40],
       [36,  1, 56]])

In [81]:
a / b

array([[1.12, 0.33, 1.4 ],
       [0.75, 1.6 , 1.6 ],
       [1.  , 1.  , 1.14]])

In [82]:
a - b

array([[ 1, -2,  2],
       [-2,  3,  3],
       [ 0,  0,  1]])

In [83]:
a.dot(b) # matrix multiplicatiom

array([[122,  39,  99],
       [160,  66, 126],
       [104,  31,  91]])

In [84]:
a * b  # not matrix multiplication

array([[72,  3, 35],
       [48, 40, 40],
       [36,  1, 56]])

In [85]:
a + 10 # add 10 to all elements

array([[19, 11, 17],
       [16, 18, 18],
       [16, 11, 18]])

In [86]:
print(a.mean())

6.0


In [90]:
print(a.mean())
print(a.mean(axis=0))  # coloumn wise mean
print(a.mean(axis=0))  # row wise mean

6.0
[7.   3.33 7.67]
[7.   3.33 7.67]


In [92]:
print(a.sum())
print(a.sum(axis=0))  # coloumn wise sum
print(a.sum(axis=0))  # row wise sum

54
[21 10 23]
[21 10 23]


In [93]:
np.sin(a)

array([[ 0.41,  0.84,  0.66],
       [-0.28,  0.99,  0.99],
       [-0.28,  0.84,  0.99]])

In [94]:
np.cos(a)

array([[-0.91,  0.54,  0.75],
       [ 0.96, -0.15, -0.15],
       [ 0.96,  0.54, -0.15]])

In [96]:
np.tan(a)

array([[-0.45,  1.56,  0.87],
       [-0.29, -6.8 , -6.8 ],
       [-0.29,  1.56, -6.8 ]])

In [97]:
print(np.exp(a))
print(np.sqrt(a))
print(np.max(a))
print(np.min(a))

[[8.10e+03 2.72e+00 1.10e+03]
 [4.03e+02 2.98e+03 2.98e+03]
 [4.03e+02 2.72e+00 2.98e+03]]
[[3.   1.   2.65]
 [2.45 2.83 2.83]
 [2.45 1.   2.83]]
9
1


In [98]:
x = np.random.randint(1,100,(2,5))
print(x)

[[21 24 82  1 84]
 [71  9 22 61 82]]


In [101]:
print(x.max())
print(x.argmax())
print(x.min())
print(x.argmin())

84
4
1
3


In [3]:
x = np.linspace(1,100,25).reshape(5,5).astype(int)
print(x)
print(x[0]) # row index 0
print(x[-1]) # last row
print(x[2]) #row index 2
print(x[:3]) # row index 0 to 2
print(x[-2:]) # last 2 row
print(x[:,0]) # coloumn index 0
print(x[:,-1]) # # last coloumn

[[  1   5   9  13  17]
 [ 21  25  29  34  38]
 [ 42  46  50  54  58]
 [ 62  67  71  75  79]
 [ 83  87  91  95 100]]
[ 1  5  9 13 17]
[ 83  87  91  95 100]
[42 46 50 54 58]
[[ 1  5  9 13 17]
 [21 25 29 34 38]
 [42 46 50 54 58]]
[[ 62  67  71  75  79]
 [ 83  87  91  95 100]]
[ 1 21 42 62 83]
[ 17  38  58  79 100]


In [5]:
print(x[2:-1,2:])

[[50 54 58]
 [71 75 79]]


# filtering


In [6]:
x > 50  # boolean filter

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [7]:
x[x>50]   # filter values greater than 50 - broadcasting

array([ 54,  58,  62,  67,  71,  75,  79,  83,  87,  91,  95, 100])

In [9]:
x[(x>40) & (x<80)] # filtering values greater than 40 and less then 80, `&` is bitwise and

array([42, 46, 50, 54, 58, 62, 67, 71, 75, 79])

In [11]:
x[x % 2 == 0] # filter even numbers

array([ 34,  38,  42,  46,  50,  54,  58,  62, 100])

# 3 rd party libraries 
- `plotly` - interactive lots using HTML 
- `matplots` - plotting library for almost all types of plots (image)
- `seaborn` - ployying library for statistical plots (extension of matplotlib)
- `statsmodels` - for support in seaborn 
- `scipy` - for support in seaborn 
- `nbformat` - for support in plotly